spring:
  application:
    name: cards
    version: 1.0
    title: Cards
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8888
    profile: ${spring.profiles.active}
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "Cards"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
eureka:
  client: ${eureka-client}
server:
  port: 9950
