spring:
  application:
    name: customer
    version: 1.0
    title: Customer
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8888
    profile: ${spring.profiles.active}
#  h2:
#    console:
#      enabled: true
  datasource:
#    initialization-mode: always
#    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh, metrics, mappings
info:
  app:
    name: "Customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
application:
  allow-get-customer: ${customer.allow-get-customer}
demo:
  name: "zażółć gęślą jaźń"
#eureka:
#  client: ${eureka-client}
feign:
  circuitbreaker:
    enabled: false
accounts:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9999,localhost:9998