spring:
        datasource:
                url: jdbc:h2:mem:cards
                username: sa
                password: 
                initialization-mode: always
                initialize: true
