server:
        port: 7778
spring:
        datasource:
                url: jdbc:h2:mem:customer
                username: sa
                password: sa
                initialization-mode: always
                initialize: true
customer:
        allow-get-customer: true