server:
        port: 7778
spring:
        datasource:
                driverClassName: org.postgresql.Driver
                url: jdbc:postgresql://192.168.2.5:5432/customer
                username: postgres
                password: test
                initialization-mode: always
                initialize: true
customer:
        allow-get-customer: true