apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-k8s
  name: kello-k8s
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32222
    selector:
      app: hello-k8s